esphome:
  name: lin-sniffer
  friendly_name: Lin Sniffer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 115200
  # level: VERY_VERBOSE
  level: VERBOSE
  # level: DEBUG
  # level: INFO
  # level: WARN
  # level: NONE

#ethernet:
  #type: KSZ8081RNA
  #mdc_pin: 23
  #mdio_pin: 18
  #clk_mode: GPIO16_OUT

time:
  - platform: homeassistant
    id: real_time

# Enable Home Assistant API
api:
  encryption:
    key: "z+ZE7EyBk4XYlv4PdGoFKSuZ31vYfZZbVLQtM9tfaCg="

ota:
  - platform: esphome
    password: "ca95692ee26d5345e19d8ac984496a09"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lin-Sniffer Fallback Hotspot"
    password: "knt9Iees7mih"

captive_portal:


external_components:
  - source:
      type: local
      path: ./custom_components

uart:
  - id: uart_lin
    tx_pin: 15    #15 12
    rx_pin: 14    #14 13
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

text_sensor:
  - platform: template
    name: "Letzter LIN Frame"
    id: last_lin_frame

lin_sniffer:
  id: alde_sniffer
  uart_id: uart_lin
  text_sensor: last_lin_frame


web_server: 
  port: 80