esphome:
  name: "lin-dec"
  friendly_name: "ALde Remote"
  

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:
  baud_rate: 2000000
  # level: VERY_VERBOSE
  # level: VERBOSE
  level: DEBUG
  # level: INFO
  # level: WARN
  # level: NONE

# Enable Home Assistant API
api:
  encryption:
    key: "dEiP/RauemVlrFjE/KcLuR/b1VQBPVGIl1/KvhSPFRE="

ota:
  - platform: esphome
    password: "e227c5b471a339a5e79835bac3e01daf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lin-Test Fallback Hotspot"
    password: "HMMOdJEQ2Gsf"

captive_portal:
    

uart:
  - id: lin_uart_bus
    tx_pin: 15    #15 12
    rx_pin: 14    #14 13
    baud_rate: 9600  #9600
    data_bits: 8
    parity: NONE
    stop_bits: 2


external_components:
  - source: github://hliebscher/esp-inetbox/supersonic
    components: [truma_inetbox]

#packages:
  #device: !include device.yaml # include our test device setup

time:
  - platform: homeassistant
    id: real_time


truma_inetbox:
  id: truma_inetbox_id
  uart_id: lin_uart_bus
  on_heater_message:
    then:
      - logger.log:
          format: "Heater status: %s"
          args:
            - 'esphome::truma_inetbox::operating_status_to_str(message->operating_status).c_str()'

web_server:
  port: 80
  local: true
  version: 2
  include_internal: true